This is the Dummy Testing File to Check the functions from Util.py

In [1]:
import pandas as pd
import os
import sqlite3
from sqlite3 import Error

from constants import *
from utils import *
from city_tier_mapping import *
from significant_categorical_level import *
import collections 
from data_validation_checks import *
from schema import *
from test_with_pytest import *

In [2]:
print(DB_PATH)
print(DB_FILE_NAME)
print(DATA_DIRECTORY)
print(INTERACTION_MAPPING)

/home/Assignment/01_data_pipeline/scripts/unit_test/
utils_output.db
/home/Assignment/01_data_pipeline/scripts/unit_test/
/home/Assignment/01_data_pipeline/scripts/mapping/interaction_mapping.csv

In [3]:
build_dbs()

DB Already Exsist

'DB Exsists'

In [4]:
load_data_into_db()

In [5]:
con = sqlite3.connect(DB_PATH + DB_FILE_NAME)
df = pd.read_sql('select * from loaded_data', con)
print(df.shape)
df.head()

(100, 45)

,created_date,city_mapped,first_platform_c,first_utm_medium_c,first_utm_source_c,total_leads_droppped,referred_lead,1_on_1_industry_mentorship,call_us_button_clicked,career_assistance,...,specilization_click,syllabus,syllabus_expand,syllabus_submodule_expand,tab_career_assistance,tab_job_opportunities,tab_student_support,view_programs_page,whatsapp_chat_click,app_complete_flag
0,2021-11-19 15:25:38,ghazipur,Level3,Level0,Level0,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,1
1,2021-08-24 15:17:20,murbad,Level3,Level0,Level0,2.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,1
2,2021-07-20 16:01:20,mumbai,Level14,Level2,Level2,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,0
3,2021-09-04 14:00:42,bengaluru,Level7,Level0,Level0,4.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,1
4,2022-01-13 05:41:45,ncr,Level8,Level16,Level2,1.0,0.0,None,None,None,...,None,None,None,None,None,None,None,None,None,0

In [6]:
df.columns

Index(['created_date', 'city_mapped', 'first_platform_c', 'first_utm_medium_c',
       'first_utm_source_c', 'total_leads_droppped', 'referred_lead',
       '1_on_1_industry_mentorship', 'call_us_button_clicked',
       'career_assistance', 'career_coach', 'career_impact', 'careers',
       'chat_clicked', 'companies', 'download_button_clicked',
       'download_syllabus', 'emi_partner_click', 'emi_plans_clicked',
       'fee_component_click', 'hiring_partners',
       'homepage_upgrad_support_number_clicked',
       'industry_projects_case_studies', 'live_chat_button_clicked',
       'payment_amount_toggle_mover', 'placement_support',
       'placement_support_banner_tab_clicked', 'program_structure',
       'programme_curriculum', 'programme_faculty',
       'request_callback_on_instant_customer_support_cta_clicked',
       'shorts_entry_click', 'social_referral_click',
       'specialisation_tab_clicked', 'specializations', 'specilization_click',
       'syllabus', 'syllabus_expand', 'syllabus_submodule_expand',
       'tab_career_assistance', 'tab_job_opportunities', 'tab_student_support',
       'view_programs_page', 'whatsapp_chat_click', 'app_complete_flag'],
      dtype='object')

In [7]:
map_city_tier()

In [8]:
con = sqlite3.connect(DB_PATH + DB_FILE_NAME)
df = pd.read_sql('select * from city_tier_mapped', con)
print(df.shape)
print(df.columns)
df.head()

(100, 45)
Index(['created_date', 'first_platform_c', 'first_utm_medium_c',
       'first_utm_source_c', 'total_leads_droppped', 'referred_lead',
       '1_on_1_industry_mentorship', 'call_us_button_clicked',
       'career_assistance', 'career_coach', 'career_impact', 'careers',
       'chat_clicked', 'companies', 'download_button_clicked',
       'download_syllabus', 'emi_partner_click', 'emi_plans_clicked',
       'fee_component_click', 'hiring_partners',
       'homepage_upgrad_support_number_clicked',
       'industry_projects_case_studies', 'live_chat_button_clicked',
       'payment_amount_toggle_mover', 'placement_support',
       'placement_support_banner_tab_clicked', 'program_structure',
       'programme_curriculum', 'programme_faculty',
       'request_callback_on_instant_customer_support_cta_clicked',
       'shorts_entry_click', 'social_referral_click',
       'specialisation_tab_clicked', 'specializations', 'specilization_click',
       'syllabus', 'syllabus_expand', 'syllabus_submodule_expand',
       'tab_career_assistance', 'tab_job_opportunities', 'tab_student_support',
       'view_programs_page', 'whatsapp_chat_click', 'app_complete_flag',
       'city_tier'],
      dtype='object')

,created_date,first_platform_c,first_utm_medium_c,first_utm_source_c,total_leads_droppped,referred_lead,1_on_1_industry_mentorship,call_us_button_clicked,career_assistance,career_coach,...,syllabus,syllabus_expand,syllabus_submodule_expand,tab_career_assistance,tab_job_opportunities,tab_student_support,view_programs_page,whatsapp_chat_click,app_complete_flag,city_tier
0,2021-11-19 15:25:38,Level3,Level0,Level0,1.0,0.0,None,None,None,None,...,None,None,None,None,None,None,None,None,1,3.0
1,2021-08-24 15:17:20,Level3,Level0,Level0,2.0,0.0,None,None,None,None,...,None,None,None,None,None,None,None,None,1,3.0
2,2021-07-20 16:01:20,Level14,Level2,Level2,1.0,0.0,None,None,None,None,...,None,None,None,None,None,None,None,None,0,1.0
3,2021-09-04 14:00:42,Level7,Level0,Level0,4.0,0.0,None,None,None,None,...,None,None,None,None,None,None,None,None,1,1.0
4,2022-01-13 05:41:45,Level8,Level16,Level2,1.0,0.0,None,None,None,None,...,None,None,None,None,None,None,None,None,0,1.0

In [9]:
map_categorical_vars()

In [10]:
con = sqlite3.connect(DB_PATH + DB_FILE_NAME)
df = pd.read_sql('select * from categorical_variables_mapped', con)
print(df.shape)
df.head()

(100, 45)

,created_date,first_platform_c,first_utm_medium_c,first_utm_source_c,total_leads_droppped,referred_lead,1_on_1_industry_mentorship,call_us_button_clicked,career_assistance,career_coach,...,syllabus,syllabus_expand,syllabus_submodule_expand,tab_career_assistance,tab_job_opportunities,tab_student_support,view_programs_page,whatsapp_chat_click,app_complete_flag,city_tier
0,2022-02-10 08:28:30,Level0,others,others,1.0,0.0,None,None,None,None,...,None,None,None,None,None,None,None,None,0,2.0
1,2021-11-12 07:02:01,Level0,others,others,1.0,0.0,None,None,None,None,...,None,None,None,None,None,None,None,None,0,1.0
2,2022-01-12 09:57:33,others,Level3,others,1.0,0.0,None,None,None,None,...,None,None,None,None,None,None,None,None,0,3.0
3,2022-02-11 09:00:25,others,Level13,others,1.0,0.0,None,None,None,None,...,None,None,None,None,None,None,None,None,0,1.0
4,2021-10-07 15:12:12,Level0,Level3,others,2.0,0.0,None,None,None,None,...,None,None,None,None,None,None,None,None,1,1.0

In [11]:
interactions_mapping()

In [12]:
con = sqlite3.connect(DB_PATH + DB_FILE_NAME)
df = pd.read_sql('select * from interactions_mapped', con)
print(df.shape)
df.head()

(100, 13)

,created_date,city_tier,first_platform_c,first_utm_medium_c,first_utm_source_c,total_leads_droppped,referred_lead,app_complete_flag,assistance_interaction,career_interaction,payment_interaction,social_interaction,syllabus_interaction
0,2021-07-01 07:32:25,1.0,Level3,others,Level16,2.0,0.0,1,0,0,0,0,0
1,2021-07-05 04:26:31,1.0,Level2,Level6,Level7,2.0,0.0,0,0,0,0,0,0
2,2021-07-08 11:28:20,1.0,Level7,Level3,Level6,1.0,0.0,1,0,0,0,0,0
3,2021-07-11 05:39:39,3.0,Level3,Level0,Level0,4.0,0.0,1,0,0,0,0,0
4,2021-07-12 16:56:30,1.0,Level3,Level0,Level0,6.0,0.0,1,0,0,0,0,0

In [13]:
raw_data_schema_check()

Raw datas schema is NOT in line with the schema present in schema.py

In [14]:
leadscoring = pd.read_csv(f"{DATA_DIRECTORY}/leadscoring_test.csv")
#leadscoring = leadscoring.iloc[:, 1:]
source_cols = leadscoring.columns.to_list()

if collections.Counter(source_cols) == collections.Counter(raw_data_schema):
    print('Raw datas schema is in line with the schema present in schema.py')
else:
    print('Raw datas schema is NOT in line with the schema present in schema.py')

Raw datas schema is in line with the schema present in schema.py

In [15]:
leadscoring.head()

,created_date,city_mapped,first_platform_c,first_utm_medium_c,first_utm_source_c,total_leads_droppped,referred_lead,1_on_1_industry_mentorship,call_us_button_clicked,career_assistance,...,specilization_click,syllabus,syllabus_expand,syllabus_submodule_expand,tab_career_assistance,tab_job_opportunities,tab_student_support,view_programs_page,whatsapp_chat_click,app_complete_flag
0,2021-11-19 15:25:38,ghazipur,Level3,Level0,Level0,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,2021-08-24 15:17:20,murbad,Level3,Level0,Level0,2.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2021-07-20 16:01:20,mumbai,Level14,Level2,Level2,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
3,2021-09-04 14:00:42,bengaluru,Level7,Level0,Level0,4.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,2022-01-13 05:41:45,ncr,Level8,Level16,Level2,1.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0

# Test_with_pytest validation (utils_output.db and unit_test_cases.db)

In [16]:
model_input_schema_check()

Models input schema is in line with the schema present in schema.py

In [17]:
test_load_data_into_db()

Reading data from loaded_data table utils_output.db
Reading data from loaded_data_test_case table

In [18]:
test_map_city_tier()

Reading data from city_tier_mapped table
Reading data from city_tier_mapped_test_case table

In [19]:
con = sqlite3.connect('/home/Assignment/01_data_pipeline/scripts/' + 'unit_test_cases.db')
df = pd.read_sql(f"SELECT name FROM sqlite_master WHERE type='table'", con)
df = pd.read_sql('select * from categorical_variables_mapped_test_case', con)
print("Test Row count",df.shape[0])
con.close()

con = sqlite3.connect('/home/Assignment/01_data_pipeline/scripts/' + 'utils_output.db')
df = pd.read_sql(f"SELECT name FROM sqlite_master WHERE type='table'", con)
df = pd.read_sql('select * from categorical_variables_mapped', con)
print("Actual Row Count",df.shape[0])
con.close()

test_map_categorical_vars()

Test Row count 100
Actual Row Count 240000
Reading data from categorical_variables_mapped table
Reading data from categorical_variables_mapped_test_case table

In [20]:
con = sqlite3.connect('/home/Assignment/01_data_pipeline/scripts/' + 'unit_test_cases.db')
df = pd.read_sql(f"SELECT name FROM sqlite_master WHERE type='table'", con)
df = pd.read_sql('select * from interactions_mapped_test_case', con)
print("Test Row count",df.shape[0])
con.close()

con = sqlite3.connect('/home/Assignment/01_data_pipeline/scripts/' + 'utils_output.db')
df = pd.read_sql(f"SELECT name FROM sqlite_master WHERE type='table'", con)
df = pd.read_sql('select * from interactions_mapped', con)
print("Actual Row Count",df.shape[0])
con.close()

test_interactions_mapping()

Test Row count 100
Actual Row Count 238964
Reading data from interactions_mapped table
Reading data from interactions_mapped_test_case table